name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::730335337132:role/learn-beanstalk-role
          aws-region: "ca-central-1"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Elastic Beanstalk Application (if not exists)
        run: |
          aws elasticbeanstalk describe-applications --region ca-central-1 | grep -q '"ApplicationName": "HelloWorldApp"' || \
          aws elasticbeanstalk create-application --application-name "HelloWorldApp" --region ca-central-1

      - name: Deploy to Elastic Beanstalk
        run: |
          zip -r app.zip .
          aws s3 cp app.zip s3://elasticbeanstalk-ca-central-1-$(aws sts get-caller-identity --query Account --output text)/app.zip

          aws elasticbeanstalk create-application-version \
            --application-name "HelloWorldApp" \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket="elasticbeanstalk-ca-central-1-$(aws sts get-caller-identity --query Account --output text)",S3Key="app.zip"

      - name: Create or Update Elastic Beanstalk Environment
        run: |
          aws elasticbeanstalk describe-environments --application-name "HelloWorldApp" --region ca-central-1 | grep -q '"EnvironmentName": "HelloWorldEnvironment"' || \
          aws elasticbeanstalk create-environment \
            --application-name "HelloWorldApp" \
            --environment-name "HelloWorldEnvironment" \
            --solution-stack-name "64bit Amazon Linux 2 v3.5.0 running Python 3.9" \
            --version-label ${{ github.sha }} \
            --option-settings file://options.json

          aws elasticbeanstalk update-environment \
            --environment-name "HelloWorldEnvironment" \
            --version-label ${{ github.sha }}
